### ISSUE TITLE
AudioMixer assertion failure

### ISSUE THREAD

**Issue by KeeVeeGames** [YoYoGames/Test-GameMaker-Bugs#66]
### Description
I attached the screenshot of the error I am getting after closing the project.

I have found that the call of audio_bus_create is causing the error, not sure if there's other audio_ functions that may do the same.

### Steps To Reproduce
1. Run the project
2. Close the project and get the error

Sometimes the error may not be yielded, after some re-runs it should appear.

[2afe04cb-d491-4ff7-b9e1-9d1e1897eb6a](https://api.gamemaker.io/api/github/downloads/2afe04cb-d491-4ff7-b9e1-9d1e1897eb6a)

**Comment by jackerley** [comment]
Fixed
