### ISSUE TITLE
Reporting a bug from IDE lost github authorization.

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/Test-GameMaker-Bugs#68]
### Description

When I was reporting a bug, I've got error that I'm unauthorised, and when sending form again, ticket was added as `gm-bug-reporter` instead from my account.

![obraz](https://github.com/YoYoGames/Test-GameMaker-Bugs/assets/524094/5e4e9624-a9ea-49b1-9c89-d68b108fe0a9)

I'm not sure if that was caused by installing new version today (the one which fixes sessions - 2023.800.0.396), or it's something else.

### Steps To Reproduce

1. Link github account
2. Logout and login in IDE
3. Create bug report

### How reliably can you recreate this issue using your steps above?

Only Ever Happened Once

### Which version of GameMaker are you reporting this issue for?

Beta (2023.800.0.396)

**Comment by gnysek** [comment]
Test ticket which I made after logging out, logging in and restarting IDE: https://github.com/YoYoGames/Test-GameMaker-Bugs/issues/69

Test ticket which I made earlier today to check if my github account is linked: https://github.com/YoYoGames/Test-GameMaker-Bugs/issues/61 - and it was working in previous beta.

**Comment by KormexGameMaker** [comment]
I also just had this happen, relogging and submitting the bug report again fixed it

**Comment by iampremo** [comment]
This should now be fixed
