### ISSUE TITLE
is_debug_overlay_open isn't working

### ISSUE THREAD

**Issue by KeeVeeGames** [YoYoGames/Test-GameMaker-Bugs#79]
### Description
Seems to be not actually added in the codebase, the function is highlighted in the IDE but not recognizable in running game.

[ee826783-8226-4f1d-afcf-b0507cdaa887](https://api.gamemaker.io/api/github/downloads/ee826783-8226-4f1d-afcf-b0507cdaa887)

**Comment by rwkay** [comment]
Thanks for catching it... it was missing from one of the files that it needs to be in... I have fixed it internally

**Comment by rwkay** [comment]
Fixed for 2023.800
